# yamllint disable rule:line-length
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# yamllint enable rule:line-length
---
name: Lint
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - test-me-*

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: python3 -m pip install yamllint
      - run: python3 -m yamllint --strict .

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: >
          npx prettier
          --check
          '**/*.{ts,tsx,json,js,mjs,cjs,yml,yaml,md}'

  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: npx tsc --project ./tsconfig.json

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: npx next lint
        env:
          SKIP_ENV_VALIDATION: 1
