name: Lint Application
on:
  pull_request:
    branches:
      - main
      - test-me-*

jobs:
  lint_app:
    name: 🧽 Lint and Typecheck Application
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3

      - name: 💻 Setup Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: "18"
          cache: "npm"

      - name: 🚧 Install Dependencies
        run: npm ci

      - name: 🧽 Run Typecheck
        run: npx tsc --project ./tsconfig.json

      - name: 🧽 Run Prettier
        run: npx prettier --check '**/*.{ts,tsx,json,js,mjs,cjs,yml,yaml,md}'

      - name: 🧽 Run ESLint
        env:
          SKIP_ENV_VALIDATION: 1
        run: npx next lint
